const model=train(TRAINING_DATA),labels=Object.keys(model.classes),allLabels=[...labels,'Needs review'];
const hypotheses={
'Lead relevance':{effort:3,test:'Test product, location and minimum-order filters before an enquiry reaches a seller.',metric:'Seller-rated relevant enquiry share',guard:'Total valid enquiries delivered; buyer completion rate'},
'Buyer responsiveness':{effort:2,test:'Test a structured follow-up reminder after a seller sends a quotation.',metric:'Buyer reply rate within 48 hours',guard:'Buyer opt-outs and notification complaints'},
'Onboarding & catalogue':{effort:4,test:'Test a guided document checklist and visible verification status.',metric:'Seller onboarding completion within seven days',guard:'Verification quality and support contacts'},
'Subscription & billing':{effort:2,test:'Test a clear renewal summary and accessible cancellation journey.',metric:'Billing-related support contacts per renewal',guard:'Refund errors and unintended cancellations'},
'App reliability':{effort:5,test:'Investigate crash logs by device and test a targeted fix with a staged rollout.',metric:'Crash-free sessions',guard:'Message delivery latency and login success'}
};
let records=[],efforts=Object.fromEntries(labels.map(l=>[l,hypotheses[l].effort]));
const $=id=>document.getElementById(id);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function annotate(row){const pred=predict(model,row.text);return {...row,pred,label:pred.label,reviewed:false};}
function visible(){return records.filter(r=>$('segment').value==='All segments'||r.segment===$('segment').value);}
function aggregate(rows){return allLabels.map(label=>{const subset=rows.filter(r=>r.label===label),count=subset.length,avg=count?subset.reduce((s,r)=>s+r.severity,0)/count:0;return {label,count,avg,score:label==='Needs review'?0:(rows.length?100*count/rows.length*avg/efforts[label]:0)};});}
function render(){const rows=visible(),groups=aggregate(rows),rank=groups.filter(g=>g.count&&g.label!=='Needs review').sort((a,b)=>b.score-a.score);$('stats').replaceChildren();for(const [v,t] of [[rows.length,'Feedback entries'],[groups.filter(g=>g.count&&g.label!=='Needs review').length,'Active themes'],[rows.filter(r=>!r.reviewed).length,'Awaiting human review'],[rows.filter(r=>r.reviewed).length,'Human-reviewed entries']]){const s=el('div',undefined,'stat');s.append(el('b',v),el('span',t));$('stats').append(s);}
$('themes').replaceChildren();for(const g of groups.filter(g=>g.count).sort((a,b)=>b.count-a.count)){const b=el('button',undefined,'theme'),line=el('div',undefined,'theme-line'),bar=el('div',undefined,'bar'),fill=el('i');line.append(el('span',g.label),el('strong',g.count+' · '+Math.round(g.count/rows.length*100)+'%'));fill.style.width=(g.count/rows.length*100)+'%';bar.append(fill);b.append(line,bar);b.onclick=()=>{$('themefilter').value=g.label;renderTable();$('queue').scrollIntoView({behavior:'smooth'});};$('themes').append(b);}if(!rows.length)$('themes').append(el('p','No feedback in this segment.'));
$('priorities').replaceChildren();for(const g of rank){const r=el('div',undefined,'rank'),info=el('div'),lab=el('label','Effort'),input=el('input');input.type='number';input.min=1;input.max=10;input.step=1;input.value=efforts[g.label];input.setAttribute('aria-label',g.label+' effort');input.onchange=()=>{efforts[g.label]=Math.max(1,Math.min(10,Math.round(Number(input.value)||1)));render();};info.append(el('strong',g.label),el('br'),el('small',g.count+' entries · severity '+g.avg.toFixed(1)));lab.append(input);r.append(info,lab,el('b',g.score.toFixed(1)));$('priorities').append(r);}
$('brief').replaceChildren(el('p','EXPERIMENT CANDIDATE / AUTHORED HYPOTHESIS','eyebrow'));if(rank.length){const top=rank[0],h=hypotheses[top.label];$('brief').append(el('h2','Investigate: '+top.label),el('p',h.test),el('p','Measure: '+h.metric+'. Guardrails: '+h.guard+'.'),el('p','Evidence: '+top.count+' entries in the current segment; '+rows.filter(r=>r.label===top.label&&!r.reviewed).length+' labels still need human review. Ranking is a discussion aid, not a roadmap commitment.','caption'));}else $('brief').append(el('p','Add or review feedback to identify an investigation candidate.'));renderTable();}
function renderTable(){const rows=visible().filter(r=>$('themefilter').value==='All themes'||r.label===$('themefilter').value);$('rows').replaceChildren();for(const r of rows){const tr=el('tr'),text=el('td'),cat=el('td'),score=el('td'),sev=el('td');text.append(el('div',r.text),el('small','#'+r.id+' · '+r.segment));const select=el('select');select.setAttribute('aria-label','Category for feedback '+r.id);for(const l of allLabels){const o=el('option',l);o.value=l;select.append(o);}select.value=r.label;select.onchange=()=>{r.label=select.value;r.reviewed=true;render();};cat.append(select,el('small','Original ML: '+r.pred.label));const review=el('button',r.reviewed?'Reviewed ✓':'Confirm label','secondary');review.style.fontSize='10px';review.style.marginTop='5px';review.onclick=()=>{r.reviewed=true;render();};cat.append(review);score.append(el('span',r.pred.scores.length?(r.pred.scores[0].score*100).toFixed(0)+'%':'N/A'),el('small','Original top score'),el('small',r.pred.evidence.join(', ')));if(r.pred.label==='Needs review')score.append(el('span','Uncertain','pill'));const s=el('select');s.setAttribute('aria-label','Severity for feedback '+r.id);for(const [v,t] of [[1,'1 · Minor'],[2,'2 · Friction'],[3,'3 · Blocker']]){const o=el('option',t);o.value=v;s.append(o);}s.value=r.severity;s.onchange=()=>{r.severity=Number(s.value);render();};sev.append(s);tr.append(text,cat,score,sev);$('rows').append(tr);}if(!rows.length){const tr=el('tr'),td=el('td','No feedback matches this filter.');td.colSpan=4;tr.append(td);$('rows').append(tr);}}
function reset(){records=SAMPLE_DATA.map(annotate);efforts=Object.fromEntries(labels.map(l=>[l,hypotheses[l].effort]));$('segment').value='All segments';$('themefilter').value='All themes';$('status').textContent='Synthetic sample workspace · Severity and effort values are assumptions. Export to keep edits.';render();}
for(const l of allLabels)$('themefilter').append(el('option',l));$('segment').onchange=render;$('themefilter').onchange=renderTable;$('reset').onclick=reset;
$('add').onclick=()=>{const lines=$('batch').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length){$('status').textContent='Enter at least one feedback entry.';return;}if(lines.length>100||records.length+lines.length>500){$('status').textContent='Limit: 100 entries per batch and 500 entries in the workspace.';return;}const seen=new Set(records.map(r=>r.text.toLowerCase())),start=records.length;for(const text of lines){if(seen.has(text.toLowerCase()))continue;seen.add(text.toLowerCase());records.push(annotate({id:records.length+1,text,segment:'Unspecified',severity:2}));}$('batch').value='';$('segment').value='All segments';$('themefilter').value='All themes';$('status').textContent=(records.length-start)+' added; '+(lines.length-(records.length-start))+' duplicates skipped. New entries default to severity 2; review before prioritising.';render();};
function csvCell(v){let s=String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
$('export').onclick=()=>{const rows=[['id','feedback','segment','ml_label','reviewed_label','human_reviewed','severity','original_top_score'],...records.map(r=>[r.id,r.text,r.segment,r.pred.label,r.label,r.reviewed,r.severity,r.pred.scores[0]?.score??''])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='sellervoice-reviewed-feedback.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Exported all '+records.length+' entries, including review status. CSV contains feedback; share appropriately.';};
const evaluation=evaluate(model,TEST_DATA);$('eval').textContent=evaluation.correct+'/'+evaluation.total+' correct ('+(evaluation.accuracy*100).toFixed(1)+'%) on separately authored synthetic test examples. Majority-class baseline: 20%. Abstentions count as incorrect.';$('matrix').textContent=JSON.stringify(evaluation,null,2);reset();
